import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def chat_with_gpt4o(text: str) -> str:
    """
    Function to interact with Gemini 2.5 pro model for text generation.
    
    Args:
        text (str): The input text to be processed by the model.
        
    Returns:
        str: The response generated by the model.
    """
    response = client.responses.create(
        model="gpt-4o-mini-2024-07-18",
        input=text,
    )
    
    return response.output_text